plugins {
    id 'com.android.library'
}

android {
    namespace 'com.android.launcher3.icons'
    compileSdk 31
    defaultConfig {
        minSdk 26
        targetSdk 31
    }
    sourceSets {
        main {
            java.srcDirs = ['src/main/java']
            manifest.srcFile 'src/main/AndroidManifest.xml'
            res.srcDirs = ['src/main/res']
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation 'androidx.core:core:1.6.0'
}
